name = "TC Essentials"
license = "MIT"
licenselink = ""
description = ""

homepage = "https://tc-essentials.oran.pw"
demosite = "https://tc-essentials.oran.pw"

tags = ["landing page", "documentation", "blog", "minimal", "modern", "customizable", "search", "dark mode", "bootstrap"]
features = ["security aware", "fast by default", "seo-ready", "development tools", "bootstrap framework", "netlify-ready", "full text search", "page layouts", "dark mode"]
