[[docs]]
  name = "Prologue"
  weight = 10
  identifier = "prologue"
  url = "/docs/prologue/"

[[docs]]
  name = "Help"
  weight = 60
  identifier = "help"
  url = "/docs/help/"

# [[docs]]
#   name = "Lorem"
#   weight = 70
#   identifier = "lorem"
#   url = "/docs/lorem/"

[[guide]]
  name = "Lorem"
  weight = 10
  identifier = "lorem"
  url = "/guide/lorem/"

[[tutorial]]
  name = "Lorem"
  weight = 10
  identifier = "lorem"
  url = "/tutorial/lorem/"


# [[main]]
#   name = "Tutorial"
#   url = "/tutorial/lorem/ipsum/"
#   weight = 15

# [[main]]
#  name = "Blog"
 # url = "/blog/"
 # weight = 20

[[main]]
  name = "Get Started"
  weight = 30
  identifier = "get-started"
  url = "/docs/prologue/introduction/"

[[main]]
  name = "Introduction"
  weight = 40
  identifier = "quick-start"
  url = "/docs/prologue/introduction/"
  parent = "get-started"

[[main]]
  name = "Basic Elements"
  weight = 50
  identifier = "quick-2"
  url = "/docs/prologue/basic-elements/"
  parent = "get-started"

[[main]]
  name = "Level 15 Guide"
  weight = 60
  identifier = "level-15-guide"
  url = "/docs/prologue/level15"
  parent = "get-started"

[[main]]
  name = "After Level 15"
  weight = 65
  identifier = "after-15-guide"
  url = "/docs/prologue/after15"
  parent = "get-started"

[[main]]
  name = "Articles"
  url = "blog"
  weight = 66

[[main]]
  name = "Forum Thread"
  url = "https://www.torn.com/forums.php#/p=threads&f=61&t=16319240"
  weight = 70


[[main]]
  name = "Discord"
  url = "https://discord.gg/JrBpEsQB5g"
  weight = 80

[[social]]
  name = "Discord"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-message-square\"><path d=\"M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z\"></path></svg>"
  url = "https://discord.gg/JrBpEsQB5g"
  post = "v0.1.0"
  weight = 10

 [[social]]
  name = "Thread"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-activity\"><polygon points=\"3 11 22 2 13 21 11 13 3 11\"></polygon></svg>"
  url = "https://www.torn.com/forums.php#/p=threads&f=61&t=16319240"
  post = "v0.1.0"
  weight = 20

 [[social]]
  name = "Github"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-activity\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/OranWeb/TCEssentials"
  post = "v0.1.0"
  weight = 30

 [[footer]]
   name = "Privacy"
   url = "/privacy-policy/"
   weight = 10
